import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import {
  concernOrder,
  functionsTouched,
  isGenerated,
  mechanicalLines,
  parseDiff,
  scopeVerdict,
  unitVerdict,
} from './scope.ts';

const fileDiff = (path: string, body: string[]) =>
  [`diff --git a/${path} b/${path}`, `--- a/${path}`, `+++ b/${path}`, ...body].join('\n');

const everyLine = (source: string) => new Set(source.split('\n').map((_, index) => index + 1));

describe('parseDiff', () => {
  it('counts added and removed lines and numbers the new side', () => {
    const [file] = parseDiff(fileDiff('src/a.rs', ['@@ -1,2 +1,2 @@', ' keep', '-old', '+new', '+more']));
    assert.equal(file.added, 2);
    assert.equal(file.removed, 1);
    assert.deepEqual(
      file.hunks[0].lines.filter((line) => line.kind === '+').map((line) => line.newLine),
      [2, 3],
    );
  });

  it('reads the similarity of a rename', () => {
    const diff = [
      'diff --git a/old.rs b/new.rs',
      'similarity index 97%',
      'rename from old.rs',
      'rename to new.rs',
      '--- a/old.rs',
      '+++ b/new.rs',
      '@@ -1 +1 @@',
      '-a',
      '+b',
    ].join('\n');
    assert.equal(parseDiff(diff)[0].similarity, 97);
  });
});

describe('isGenerated', () => {
  it('recognises lockfiles and generator headers', () => {
    assert.equal(isGenerated('Cargo.lock'), true);
    assert.equal(
      isGenerated('.github/workflows/check.yaml', '# Generated by cdkactions. Do not modify\non: push'),
      true,
    );
    assert.equal(isGenerated('src/lib.rs', 'use std::fmt;'), false);
  });
});

describe('mechanicalLines', () => {
  it('counts an edit repeated across five files as mechanical and a one-off as hand-written', () => {
    const sweep = (path: string) =>
      fileDiff(path, [
        '@@ -1,2 +1,2 @@',
        '-let client = OldClient::new();',
        '+let client = NewClient::new();',
        ' done();',
      ]);
    const oneOff = fileDiff('src/feature.rs', ['@@ -1 +1,2 @@', ' fn main() {', '+    launch_feature();']);
    const files = parseDiff([...['a', 'b', 'c', 'd', 'e'].map((name) => sweep(`src/${name}.rs`)), oneOff].join('\n'));
    const mechanical = mechanicalLines(files);
    assert.equal(mechanical.get('src/a.rs'), 2);
    assert.equal(mechanical.get('src/feature.rs'), 0);
  });
});

describe('functionsTouched', () => {
  it('measures a touched Rust function and skips untouched ones', () => {
    const source = [
      'pub fn first(left: u32, verbose: bool) -> u32 {',
      '    if verbose {',
      '        return left;',
      '    }',
      '    left + 1',
      '}',
      '',
      'fn second() {}',
    ].join('\n');
    const [unit, ...rest] = functionsTouched('src/lib.rs', source, new Set([3]));
    assert.equal(rest.length, 0);
    assert.equal(unit.name, 'first');
    assert.equal(unit.params, 2);
    assert.equal(unit.flagParams, 1);
    assert.equal(unit.maxNesting, 1);
  });

  it('skips a method under #[cfg(test)] but keeps the functions after it', () => {
    const source = [
      'impl Exec {',
      '    #[cfg(test)]',
      '    fn sk_range(&self) -> u32 {',
      '        1',
      '    }',
      '    fn execute(&self) -> u32 {',
      '        2',
      '    }',
      '}',
    ].join('\n');
    assert.deepEqual(
      functionsTouched('src/exec.rs', source, everyLine(source)).map((unit) => unit.name),
      ['execute'],
    );
  });

  it('stops at the test module and ignores test files', () => {
    const source = ['fn live() {', '    1', '}', '#[cfg(test)]', 'mod tests {', '    fn helper() {}', '}'].join('\n');
    assert.deepEqual(
      functionsTouched('src/lib.rs', source, everyLine(source)).map((unit) => unit.name),
      ['live'],
    );
    assert.deepEqual(functionsTouched('src/thing.test.ts', 'function helper() {\n}', new Set([1])), []);
  });

  it('counts parameters the body branches on, not ones it forwards', () => {
    const source = [
      'fn record(&self, reason: InsertBypassReason, verbose: bool) {',
      '    self.metrics.record(reason);',
      '    if verbose {',
      '        tracing::info!("bypassed");',
      '    }',
      '}',
    ].join('\n');
    const [unit] = functionsTouched('src/cache.rs', source, everyLine(source));
    assert.equal(unit.branchedParams, 1);
    const tsSource = [
      'function label(mode: Mode, name: string) {',
      "  return mode === 'a' ? format(name) : name;",
      '}',
    ].join('\n');
    assert.equal(functionsTouched('src/label.ts', tsSource, everyLine(tsSource))[0].branchedParams, 1);
  });

  it('reads TypeScript arrow functions', () => {
    const source = [
      'export const getItem = (key: string, parser = JSON.parse) => {',
      '  return parser(key);',
      '};',
    ].join('\n');
    const [unit] = functionsTouched('src/storage.ts', source, everyLine(source));
    assert.equal(unit.name, 'getItem');
    assert.equal(unit.params, 2);
  });
});

describe('concernOrder', () => {
  it('orders a definition before its user and flags two concerns that use each other', () => {
    const order = concernOrder(
      new Map([
        ['helpers', 'pub fn env_or(name: &str) -> String {}'],
        ['config', 'pub struct WebApiConfig {}\nlet port = env_or("PORT");'],
        ['cache', 'pub struct CacheBudget {}\nlet config = WebApiConfig {};'],
        ['web', 'fn serve() { let budget = CacheBudget {}; }\nfn connect_cache() {}'],
      ]),
    );
    assert.deepEqual(order.before, [
      ['helpers', 'config'],
      ['config', 'cache'],
      ['cache', 'web'],
    ]);
    const entangled = concernOrder(
      new Map([
        ['admission', 'fn charge_insert() {}\nbytes_cached();'],
        ['accounting', 'fn bytes_cached() {}\ncharge_insert();'],
      ]),
    );
    assert.deepEqual(entangled.entangled, [['admission', 'accounting']]);
  });

  it('ignores trait methods and names mentioned only in comments', () => {
    const order = concernOrder(
      new Map([
        ['config', 'fn default() -> Self {}\nfn from_env() {}'],
        ['helpers', '// Called from from_env.\nfn env_or() { default() }'],
      ]),
    );
    assert.deepEqual(order, { before: [], entangled: [] });
  });
});

describe('scopeVerdict', () => {
  it('passes a small change without asking for concerns', () => {
    assert.equal(scopeVerdict({ handLines: 120, multipleProblems: 0.2, linesByConcern: null }).verdict, 'one-problem');
  });

  it('asks for concerns on a large change', () => {
    assert.equal(
      scopeVerdict({ handLines: 900, multipleProblems: 0.3, linesByConcern: null }).verdict,
      'propose-concerns',
    );
  });

  it('splits when two concerns each carry a substantial share', () => {
    const verdict = scopeVerdict({
      handLines: 1800,
      multipleProblems: 0.3,
      linesByConcern: new Map([
        ['admission', 925],
        ['bench', 342],
        ['wiring', 50],
      ]),
    });
    assert.equal(verdict.verdict, 'split');
  });

  it('keeps one problem when the second concern is a small helper', () => {
    const verdict = scopeVerdict({
      handLines: 1185,
      multipleProblems: 0.4,
      linesByConcern: new Map([
        ['central-config', 916],
        ['env-helpers', 26],
        ['wiring', 242],
      ]),
    });
    assert.equal(verdict.verdict, 'one-problem');
  });
});

describe('unitVerdict', () => {
  const quiet = { severalJobs: 0.1, invariantInProse: 0.1, flagParameter: 0.1, duplicate: null };

  it('suggests extraction only for a function long enough to need it', () => {
    const busy = { ...quiet, severalJobs: 0.9 };
    assert.deepEqual(unitVerdict(busy, { bodyLines: 12, params: 1, flagParams: 0, branchedParams: 0 }).actions, [
      'keep',
    ]);
    assert.deepEqual(unitVerdict(busy, { bodyLines: 45, params: 1, flagParams: 0, branchedParams: 0 }).actions, [
      'extract',
    ]);
  });

  it('lets a boolean the body branches on tip a borderline flag question', () => {
    const borderline = { ...quiet, flagParameter: 0.45 };
    assert.deepEqual(unitVerdict(borderline, { bodyLines: 9, params: 2, flagParams: 1, branchedParams: 1 }).actions, [
      'split-flag',
    ]);
    assert.deepEqual(unitVerdict(borderline, { bodyLines: 9, params: 2, flagParams: 0, branchedParams: 1 }), {
      actions: ['keep'],
      uncertain: ['flagParameter'],
    });
  });

  it('never splits a parameter the body only forwards', () => {
    const forwarded = { ...quiet, flagParameter: 0.9 };
    assert.deepEqual(unitVerdict(forwarded, { bodyLines: 4, params: 1, flagParams: 0, branchedParams: 0 }), {
      actions: ['keep'],
      uncertain: [],
    });
  });

  it('asks for a type when the invariant lives in prose', () => {
    const pairing = { ...quiet, invariantInProse: 0.85 };
    assert.deepEqual(unitVerdict(pairing, { bodyLines: 20, params: 1, flagParams: 0, branchedParams: 0 }).actions, [
      'type-the-invariant',
    ]);
  });
});
