// Measures a diff's scope and the functions it touches, and turns Jev's
// answers into the verdicts the scope-audit skill reasons about. Pure
// functions only, so scope.test.ts covers everything but the network.

export type DiffLine = { kind: '+' | '-' | ' '; text: string; newLine?: number };
export type Hunk = { lines: DiffLine[] };
export type FileDiff = {
  path: string;
  hunks: Hunk[];
  added: number;
  removed: number;
  /** `similarity index` of a rename or copy, 0 to 100. */
  similarity?: number;
};

export function parseDiff(diff: string): FileDiff[] {
  const files: FileDiff[] = [];
  let file: FileDiff | undefined;
  let hunk: Hunk | undefined;
  let newLine = 0;
  for (const raw of diff.split('\n')) {
    if (raw.startsWith('diff --git ')) {
      const target = raw.split(' b/').pop() ?? '';
      file = { path: target, hunks: [], added: 0, removed: 0 };
      files.push(file);
      hunk = undefined;
      continue;
    }
    if (!file) {
      continue;
    }
    const similarity = raw.match(/^similarity index (\d+)%/);
    if (similarity) {
      file.similarity = Number(similarity[1]);
      continue;
    }
    if (raw.startsWith('+++ ')) {
      const target = raw.slice(4).trim();
      if (target !== '/dev/null') {
        file.path = target.replace(/^b\//, '');
      }
      continue;
    }
    if (raw.startsWith('--- ')) {
      continue;
    }
    const header = raw.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
    if (header) {
      newLine = Number(header[1]);
      hunk = { lines: [] };
      file.hunks.push(hunk);
      continue;
    }
    if (!hunk || raw.startsWith('\\')) {
      continue;
    }
    const kind = raw[0];
    if (kind === '+') {
      hunk.lines.push({ kind, text: raw.slice(1), newLine });
      file.added++;
      newLine++;
    } else if (kind === '-') {
      hunk.lines.push({ kind, text: raw.slice(1) });
      file.removed++;
    } else if (kind === ' ') {
      hunk.lines.push({ kind, text: raw.slice(1), newLine });
      newLine++;
    }
  }
  return files;
}

const GENERATED_PATH =
  /(^|\/)(Cargo\.lock|Cargo\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb?|flake\.lock|devenv\.lock|go\.sum|poetry\.lock|uv\.lock|composer\.lock|Gemfile\.lock)$|(^|\/)(__generated__|generated|\.sqlx)\/|\.(generated|gen)\.[a-z]+$|\.snap$|\.min\.(js|css)$/;

const GENERATED_MARKER = /@generated|DO NOT (EDIT|MODIFY)|\bGenerated by\b|auto-?generated/i;

/** A generated file is reviewed through its generator, so its lines are not the author's. */
export function isGenerated(path: string, head?: string): boolean {
  if (GENERATED_PATH.test(path)) {
    return true;
  }
  return head !== undefined && GENERATED_MARKER.test(head.split('\n').slice(0, 5).join('\n'));
}

/** Lines of a one-for-one rewrite, as a repository-wide rename or lint fix produces. */
function swapSignature(before: string, after: string): string | undefined {
  const oldTokens = before.trim().split(/(\W)/).filter(Boolean);
  const newTokens = after.trim().split(/(\W)/).filter(Boolean);
  let head = 0;
  while (head < oldTokens.length && head < newTokens.length && oldTokens[head] === newTokens[head]) {
    head++;
  }
  let tail = 0;
  while (
    tail < oldTokens.length - head &&
    tail < newTokens.length - head &&
    oldTokens[oldTokens.length - 1 - tail] === newTokens[newTokens.length - 1 - tail]
  ) {
    tail++;
  }
  const removedTokens = oldTokens.slice(head, oldTokens.length - tail);
  const addedTokens = newTokens.slice(head, newTokens.length - tail);
  if (removedTokens.length > 4 || addedTokens.length > 4) {
    return undefined;
  }
  return `${removedTokens.join('')}→${addedTokens.join('')}`;
}

type Edit = { signature: string; lines: number };

function editsOf(file: FileDiff): Edit[] {
  const edits: Edit[] = [];
  for (const hunk of file.hunks) {
    let index = 0;
    while (index < hunk.lines.length) {
      if (hunk.lines[index].kind === ' ') {
        index++;
        continue;
      }
      const removed: string[] = [];
      const added: string[] = [];
      while (index < hunk.lines.length && hunk.lines[index].kind !== ' ') {
        const line = hunk.lines[index];
        (line.kind === '-' ? removed : added).push(line.text);
        index++;
      }
      if (removed.length === added.length) {
        for (let pair = 0; pair < removed.length; pair++) {
          const signature = swapSignature(removed[pair], added[pair]);
          edits.push({ signature: signature ?? `${removed[pair].trim()}⇒${added[pair].trim()}`, lines: 2 });
        }
      } else {
        for (const text of removed) {
          edits.push({ signature: `-${text.trim()}`, lines: 1 });
        }
        for (const text of added) {
          edits.push({ signature: `+${text.trim()}`, lines: 1 });
        }
      }
    }
  }
  return edits;
}

/**
 * Changed lines per file that repeat an edit made in at least `minFiles` files,
 * plus every line of a rename at 90% similarity or more.
 */
export function mechanicalLines(files: FileDiff[], minFiles = 5): Map<string, number> {
  const editsByFile = new Map(files.map((file) => [file.path, editsOf(file)]));
  const filesBySignature = new Map<string, Set<string>>();
  for (const [path, edits] of editsByFile) {
    for (const edit of edits) {
      if (edit.signature.trim().length <= 2) {
        continue;
      }
      const owners = filesBySignature.get(edit.signature) ?? new Set();
      owners.add(path);
      filesBySignature.set(edit.signature, owners);
    }
  }
  const result = new Map<string, number>();
  for (const file of files) {
    if ((file.similarity ?? 0) >= 90) {
      result.set(file.path, file.added + file.removed);
      continue;
    }
    let lines = 0;
    for (const edit of editsByFile.get(file.path)!) {
      if ((filesBySignature.get(edit.signature)?.size ?? 0) >= minFiles) {
        lines += edit.lines;
      }
    }
    result.set(file.path, lines);
  }
  return result;
}

export type FunctionUnit = {
  path: string;
  name: string;
  startLine: number;
  endLine: number;
  signature: string;
  text: string;
  params: number;
  flagParams: number;
  /** Parameters the body branches on with `if`, `match` or a ternary. */
  branchedParams: number;
  bodyLines: number;
  maxNesting: number;
  commentLines: number;
};

const RUST_FN = /^\s*(?:pub(?:\([^)]*\))?\s+)?(?:const\s+)?(?:async\s+)?(?:unsafe\s+)?(?:extern\s+"\w+"\s+)?fn\s+(\w+)/;
const TS_FUNCTION = /^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s*\*?\s*(\w+)/;
const TS_ARROW = /^\s*(?:export\s+)?(?:const|let)\s+(\w+)\s*(?::[^=]+)?=\s*(?:async\s+)?(?:<[^>]*>)?\s*\(/;
const TS_METHOD =
  /^\s+(?:(?:public|private|protected|static|async|override|readonly)\s+)*(?!if\b|for\b|while\b|switch\b|catch\b|return\b|new\b)(\w+)\s*(?:<[^>]*>)?\s*\(/;

function functionName(path: string, line: string): string | undefined {
  if (path.endsWith('.rs')) {
    return line.match(RUST_FN)?.[1];
  }
  if (/\.(m|c)?[jt]sx?$/.test(path)) {
    return line.match(TS_FUNCTION)?.[1] ?? line.match(TS_ARROW)?.[1] ?? line.match(TS_METHOD)?.[1];
  }
  return undefined;
}

/** Strips string literals and line comments so braces and commas count only as code. */
function codeOnly(line: string, rust: boolean): string {
  let out = '';
  let quote: string | undefined;
  for (let index = 0; index < line.length; index++) {
    const char = line[index];
    if (quote) {
      if (char === '\\') {
        index++;
      } else if (char === quote) {
        quote = undefined;
      }
      continue;
    }
    if (char === '/' && line[index + 1] === '/') {
      break;
    }
    if (char === '"' || char === '`' || (char === "'" && !rust)) {
      quote = char;
      continue;
    }
    out += char;
  }
  return out;
}

function splitTopLevel(text: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = '';
  for (const char of text) {
    if ('([{<'.includes(char)) {
      depth++;
    } else if (')]}>'.includes(char)) {
      depth--;
    }
    if (char === ',' && depth === 0) {
      parts.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  if (current.trim()) {
    parts.push(current);
  }
  return parts.map((part) => part.trim()).filter(Boolean);
}

function parameterList(signature: string): string[] {
  const open = signature.indexOf('(');
  if (open === -1) {
    return [];
  }
  let depth = 0;
  for (let index = open; index < signature.length; index++) {
    if (signature[index] === '(') {
      depth++;
    } else if (signature[index] === ')') {
      depth--;
      if (depth === 0) {
        return splitTopLevel(signature.slice(open + 1, index)).filter(
          (parameter) => !/^&?(?:'\w+\s+)?(?:mut\s+)?self$/.test(parameter) && parameter !== 'self',
        );
      }
    }
  }
  return [];
}

const FLAG_PARAMETER = /:\s*(?:bool|boolean)\b/;

function parameterName(parameter: string): string | undefined {
  return parameter
    .replace(/^(?:mut\s+|readonly\s+|public\s+|private\s+|protected\s+)+/, '')
    .match(/^([A-Za-z_]\w*)\s*[?:=]/)?.[1];
}

function branchesOn(body: string, name: string): boolean {
  const escaped = name.replace(/[$]/g, '\\$');
  return new RegExp(
    [
      `\\b(?:if|match|while|switch)\\s*\\(?\\s*!?\\s*${escaped}\\b`,
      `\\b${escaped}\\s*\\?(?![.?])`,
      `\\b${escaped}\\s*(?:===?|!==?)`,
      `\\bif\\s+let\\s+[^=]+=\\s*${escaped}\\b`,
    ].join('|'),
  ).test(body);
}

const TEST_PATH =
  /(^|\/)(tests?|__tests__|benches|test_support|fixtures)(\/|\.rs$)|_tests?\.rs$|\.(test|spec|stories|bench)\.[cm]?[jt]sx?$/;
const TEST_ATTRIBUTE = /^\s*#\[(?:(?:[\w:]+::)?(?:test|rstest|bench)\b|cfg\(test\))/;

/** Tests and benchmarks are held to their own standard, which the test reviewer owns. */
export function isTestPath(path: string): boolean {
  return TEST_PATH.test(path);
}

/** Every non-test function whose span contains an added line. */
export function functionsTouched(path: string, source: string, added: Set<number>): FunctionUnit[] {
  if (isTestPath(path)) {
    return [];
  }
  const rust = path.endsWith('.rs');
  const lines = source.split('\n');
  // A Rust file's unit tests follow its `#[cfg(test)]` module.
  const testsFrom = rust
    ? lines.findIndex(
        (line, index) => /^\s*#\[cfg\(test\)\]/.test(line) && /^\s*(pub\s+)?mod\s/.test(lines[index + 1] ?? ''),
      )
    : -1;
  const units: FunctionUnit[] = [];
  for (let index = 0; index < lines.length; index++) {
    if (testsFrom !== -1 && index >= testsFrom) {
      break;
    }
    const name = functionName(path, lines[index]);
    if (!name || lines.slice(Math.max(0, index - 3), index).some((line) => TEST_ATTRIBUTE.test(line))) {
      continue;
    }
    let depth = 0;
    let opened = false;
    let end = -1;
    let signature = '';
    let maxDepth = 0;
    for (let cursor = index; cursor < lines.length; cursor++) {
      const code = codeOnly(lines[cursor], rust);
      if (!opened) {
        const brace = code.indexOf('{');
        const semicolon = code.indexOf(';');
        if (semicolon !== -1 && (brace === -1 || semicolon < brace)) {
          break;
        }
        signature += `${brace === -1 ? code : code.slice(0, brace)} `;
      }
      for (const char of code) {
        if (char === '{') {
          depth++;
          opened = true;
          maxDepth = Math.max(maxDepth, depth);
        } else if (char === '}') {
          depth--;
        }
      }
      if (opened && depth <= 0) {
        end = cursor;
        break;
      }
    }
    if (end === -1) {
      continue;
    }
    let touched = false;
    for (let line = index + 1; line <= end + 1; line++) {
      if (added.has(line)) {
        touched = true;
        break;
      }
    }
    if (touched) {
      const body = lines.slice(index, end + 1);
      const parameters = parameterList(signature);
      const bodyCode = body
        .slice(1)
        .map((line) => codeOnly(line, rust))
        .join('\n');
      units.push({
        path,
        name,
        startLine: index + 1,
        endLine: end + 1,
        signature: signature.replace(/\s+/g, ' ').trim(),
        text: body.join('\n'),
        params: parameters.length,
        flagParams: parameters.filter((parameter) => FLAG_PARAMETER.test(parameter)).length,
        branchedParams: parameters.filter((parameter) => {
          const name = parameterName(parameter);
          return name !== undefined && branchesOn(bodyCode, name);
        }).length,
        bodyLines: body.filter((line) => line.trim()).length,
        maxNesting: Math.max(0, maxDepth - 1),
        commentLines: body.filter((line) => /^\s*(\/\/|\*|\/\*)/.test(line)).length,
      });
    }
  }
  return units;
}

// Items another concern can depend on. Local bindings are left out because
// names like `cache` or `batch` recur everywhere and would link every concern.
const DEFINITION =
  /\b(?:fn|struct|enum|trait|type|static|mod|class|interface|function)\s+([A-Za-z_]\w{3,})|\bconst\s+([A-Z_][A-Z0-9_]{3,})\b|\b(?:export\s+const)\s+([A-Za-z_]\w{3,})/g;

// Every type implements these, so a shared name says nothing about which concern needs which.
const TRAIT_METHODS = new Set([
  'default',
  'from',
  'into',
  'try_from',
  'try_into',
  'fmt',
  'drop',
  'clone',
  'hash',
  'next',
  'deref',
  'as_ref',
  'from_str',
  'poll',
  'call',
  'render',
  'toString',
  'constructor',
  'main',
]);

/** Items a set of added code lines defines, and every identifier the code mentions. */
export function identifiers(addedText: string): { defined: Set<string>; used: Set<string> } {
  const code = addedText
    .split('\n')
    .filter((line) => !/^\s*(\/\/|\/\*|\*|#(?!\[))/.test(line))
    .map((line) => codeOnly(line, false))
    .join('\n');
  const defined = new Set<string>();
  for (const match of code.matchAll(DEFINITION)) {
    const name = match[1] ?? match[2] ?? match[3];
    if (!TRAIT_METHODS.has(name)) {
      defined.add(name);
    }
  }
  const used = new Set(code.match(/[A-Za-z_]\w{3,}/g) ?? []);
  return { defined, used };
}

export type ConcernOrder = { before: [string, string][]; entangled: [string, string][] };

/**
 * `before` holds `[owner, user]`: `user` mentions an item `owner` defines, so
 * `owner` lands first. Two concerns that each use the other's items are
 * `entangled`, which a split resolves by moving the shared items to the one
 * that lands first.
 */
export function concernOrder(addedTextByConcern: Map<string, string>): ConcernOrder {
  const symbols = new Map([...addedTextByConcern].map(([concern, text]) => [concern, identifiers(text)]));
  const uses = (user: string, owner: string) => {
    const { defined } = symbols.get(owner)!;
    const { used } = symbols.get(user)!;
    return [...defined].some((name) => used.has(name));
  };
  const concerns = [...symbols.keys()];
  const before: [string, string][] = [];
  const entangled: [string, string][] = [];
  for (const [index, first] of concerns.entries()) {
    for (const second of concerns.slice(index + 1)) {
      const firstUsesSecond = uses(first, second);
      const secondUsesFirst = uses(second, first);
      if (firstUsesSecond && secondUsesFirst) {
        entangled.push([first, second]);
      } else if (firstUsesSecond) {
        before.push([second, first]);
      } else if (secondUsesFirst) {
        before.push([first, second]);
      }
    }
  }
  return { before, entangled };
}

export type Thresholds = {
  flag: number;
  uncertainLow: number;
  /** A concern carrying at least this share of the hand-written lines could be its own PR. */
  concernShare: number;
  concernLinesMin: number;
  /** Below this many hand-written lines a PR is small enough to read whole. */
  smallChangeLines: number;
  /** Below this many body lines a function reads whole, so extraction is not suggested. */
  extractLinesMin: number;
  /** A function body longer than this is weighed for extraction even without a Jev flag. */
  longFunctionLines: number;
  wideSignatureParams: number;
};

export const DEFAULT_THRESHOLDS: Thresholds = {
  flag: 0.7,
  uncertainLow: 0.35,
  concernShare: 0.15,
  concernLinesMin: 40,
  smallChangeLines: 200,
  extractLinesMin: 40,
  longFunctionLines: 60,
  wideSignatureParams: 5,
};

export type ScopeSignals = {
  handLines: number;
  multipleProblems: number | null;
  /** Hand-written lines per concern id, after the Choice assigned each file. */
  linesByConcern: Map<string, number> | null;
};

export type ScopeVerdict = { verdict: 'one-problem' | 'split' | 'propose-concerns'; reasons: string[] };

/**
 * A description written well reads as one problem even over a tangled diff, so
 * only the files decide a split; the description can only demand that they be
 * checked.
 */
export function scopeVerdict(signals: ScopeSignals, thresholds: Thresholds = DEFAULT_THRESHOLDS): ScopeVerdict {
  const reasons: string[] = [];
  const namesSeveral = (signals.multipleProblems ?? 0) >= thresholds.flag;
  if (namesSeveral) {
    reasons.push('the description names more than one problem');
  }
  if (signals.handLines < thresholds.smallChangeLines && !namesSeveral) {
    return { verdict: 'one-problem', reasons: [`${signals.handLines} hand-written lines`] };
  }
  if (signals.linesByConcern === null) {
    reasons.push(`${signals.handLines} hand-written lines`);
    return { verdict: 'propose-concerns', reasons };
  }
  const floor = Math.max(thresholds.concernLinesMin, thresholds.concernShare * signals.handLines);
  const substantial = [...signals.linesByConcern]
    .filter(([concern, lines]) => concern !== 'wiring' && concern !== 'unrelated' && lines >= floor)
    .map(([concern]) => concern);
  if (substantial.length >= 2) {
    reasons.push(`concerns ${substantial.join(', ')} each carry at least ${Math.round(floor)} lines`);
    return { verdict: 'split', reasons };
  }
  const unrelated = signals.linesByConcern.get('unrelated') ?? 0;
  if (unrelated >= floor) {
    reasons.push(`${unrelated} lines serve none of the concerns`);
    return { verdict: 'split', reasons };
  }
  return { verdict: 'one-problem', reasons };
}

export type UnitSignals = {
  severalJobs: number;
  invariantInProse: number;
  flagParameter: number;
  duplicate: number | null;
};

export type UnitAction = 'extract' | 'type-the-invariant' | 'split-flag' | 'merge-duplicate' | 'keep';

/** Below this many body lines a near-threshold signal is not worth a reader's second look. */
const UNCERTAIN_LINES_MIN = 8;

export function unitVerdict(
  signals: UnitSignals,
  unit: Pick<FunctionUnit, 'bodyLines' | 'flagParams' | 'branchedParams' | 'params'>,
  thresholds: Thresholds = DEFAULT_THRESHOLDS,
): { actions: UnitAction[]; uncertain: string[] } {
  const actions = new Set<UnitAction>();
  const uncertain: string[] = [];
  const weigh = (name: string, probability: number | null, action: UnitAction, nudged: boolean) => {
    if (probability === null) {
      return;
    }
    if (probability >= thresholds.flag || (nudged && probability >= thresholds.uncertainLow)) {
      actions.add(action);
    } else if (probability >= thresholds.uncertainLow) {
      uncertain.push(name);
    }
  };
  if (unit.bodyLines >= thresholds.extractLinesMin) {
    weigh('severalJobs', signals.severalJobs, 'extract', unit.bodyLines > thresholds.longFunctionLines);
  }
  weigh('invariantInProse', signals.invariantInProse, 'type-the-invariant', false);
  // A parameter the body only stores or forwards selects no behaviour, however it is typed.
  if (unit.branchedParams > 0) {
    weigh('flagParameter', signals.flagParameter, 'split-flag', unit.flagParams > 0);
  }
  weigh('duplicate', signals.duplicate, 'merge-duplicate', false);
  if (actions.size === 0) {
    return { actions: ['keep'], uncertain: unit.bodyLines >= UNCERTAIN_LINES_MIN ? uncertain : [] };
  }
  return { actions: [...actions], uncertain: [] };
}
